version: "3.9"

services:
  backend:
    build: ./backend
    container_name: todo_backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend/todo_frontend
    container_name: todo_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
